project:
  type: book  
  output-dir: docs

book:
  title: "Sharknado Probability Risk Analysis"
  author: "Tyler Brown"
  page-footer:
    left: "Copyright 2026, Tyler Brown"
  chapters:
    - index.qmd
    - executive_summary.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - conclusion.qmd
    - references.qmd
  appendices:
    - draft-data-doc.qmd
    - draft-results.qmd
    - draft-intro-conclusions.qmd
    - draft-exec-summary.qmd

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo

