---
title: "Conclusion"
format: html
---
The analysis demonstrates that even under highly favorable assumptions, the probability of a sharknado occurring remains extremely low. By breaking down the event into a series of necessary events, each with a very small likelihood, the combined probability becomes effectively zero. Notably, the assumption that sharks are always available along the coastline and that tornadoes of sufficient magnitude can lift them inland represents a significant overestimation, reinforcing that the calculated probability serves as a conservative upper estimate, rather than a realistic expectation.

This extremely low probability is to be expected as we are forcing many rare events to occur simultaneously. When this happens, the overall probability decreases dramatically. This idea extends beyond the concept of sharknadoes and is relevant for other concerns where many rare events need to occur together. In these scenarios, the overall likelihood will drop dramatically as the sharknado probability did.

Future work could build upon this analysis by incorporating more realistic environmental constraints, such as the distribution of shark locations and the physics-based modeling of lifting forces required for moving sharks. Ultimately, while sharnadoes are far from realistic, the analytical approach used in this study shows the power of probabilistic reasoning in exploring even the most unusual problems.
